Features/more results page
gsiri-code/nourish pull request #11
Opened 2023-03-27 02:36 UTC by gsiri-code

2023-03-30 03:05 UTC, 1mpossible-code requested changes

2023-03-30 03:05 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +#arrow {
Using ids in css is a bad practice.

2023-03-30 03:05 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +#title-static-text {
Using ids in css is a bad practice.

2023-03-30 03:05 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +#dumpling-container {
Using ids in css is a bad practice.

2023-03-30 03:05 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +#arrow:hover {
Using ids in css is a bad practice.

2023-03-30 03:05 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +    #dumpling-container {
Using ids in css is a bad practice.

2023-03-30 03:05 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +    #dumpling-container > img {
Using ids in css is a bad practice.

2023-03-30 03:05 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +    #dumpling-container > img {
And try to create a specific class for image

2023-03-30 03:05 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +    #dumpling-container{
Using ids in css is a bad practice.

2023-03-30 03:05 UTC, 1mpossible-code commented on app/templates/new-results-page.html
> +    <title>Title</title>
Make a custom title please

2023-03-30 03:05 UTC, 1mpossible-code commented on app/templates/new-results-page.html
> +<main class="results-area">
Create a better name for class results-area

2023-05-13 20:28 UTC, 1mpossible-code requested changes

2023-05-13 20:28 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +[class="fa-solid fa-arrow-left"] {
Fix notation

2023-05-13 20:28 UTC, 1mpossible-code commented on app/static/new-results-page/style-new-results-page.css
> +[class="fa-solid fa-arrow-left"]:hover {
Bad notation

2023-05-13 20:28 UTC, 1mpossible-code commented on app/templates/new-results-page.html
> +    <title>Nourish:More Results</title>
Add space

2023-05-13 21:24 UTC, gsiri-code commented on app/templates/new-results-page.html
> +    <title>Nourish:More Results</title>
> Add space

where 💀💀💀

2023-05-13 21:25 UTC, 1mpossible-code commented on app/templates/new-results-page.html
> +    <title>Nourish:More Results</title>
between nourish and more results

2023-05-13 21:25 UTC, gsiri-code commented on app/templates/new-results-page.html
> +    <title>Nourish:More Results</title>
> between nourish and more results

ahhh i got it

2023-05-20 22:22 UTC, 1mpossible-code approved these changes

2023-05-24 20:10 UTC, merged